const countries = [
  {id:"afg", flag:"🇦🇫", name:"Afghanistan"},
  {id:"alb", flag:"🇦🇱", name:"Albania"},
  {id:"dza", flag:"🇩🇿", name:"Algeria"},
  {id:"and", flag:"🇦🇩", name:"Andorra"},
  {id:"ago", flag:"🇦🇴", name:"Angola"},
  {id:"atg", flag:"🇦🇬", name:"Antigua and Barbuda"},
  {id:"arg", flag:"🇦🇷", name:"Argentina"},
  {id:"arm", flag:"🇦🇲", name:"Armenia"},
  {id:"aus", flag:"🇦🇺", name:"Australia"},
  {id:"aut", flag:"🇦🇹", name:"Austria"},
  {id:"aze", flag:"🇦🇿", name:"Azerbaijan"},
  {id:"bhs", flag:"🇧🇸", name:"Bahamas"},
  {id:"bhr", flag:"🇧🇭", name:"Bahrain"},
  {id:"bgd", flag:"🇧🇩", name:"Bangladesh"},
  {id:"brb", flag:"🇧🇧", name:"Barbados"},
  {id:"blr", flag:"🇧🇾", name:"Belarus"},
  {id:"bel", flag:"🇧🇪", name:"Belgium"},
  {id:"blz", flag:"🇧🇿", name:"Belize"},
  {id:"ben", flag:"🇧🇯", name:"Benin"},
  {id:"btn", flag:"🇧🇹", name:"Bhutan"},
  {id:"bol", flag:"🇧🇴", name:"Bolivia"},
  {id:"bih", flag:"🇧🇦", name:"Bosnia and Herzegovina"},
  {id:"bwa", flag:"🇧🇼", name:"Botswana"},
  {id:"bra", flag:"🇧🇷", name:"Brazil"},
  {id:"brn", flag:"🇧🇳", name:"Brunei"},
  {id:"bgr", flag:"🇧🇬", name:"Bulgaria"},
  {id:"bfa", flag:"🇧🇫", name:"Burkina Faso"},
  {id:"bdi", flag:"🇧🇮", name:"Burundi"},
  {id:"cpv", flag:"🇨🇻", name:"Cabo Verde"},
  {id:"khm", flag:"🇰🇭", name:"Cambodia"},
  {id:"cmr", flag:"🇨🇲", name:"Cameroon"},
  {id:"can", flag:"🇨🇦", name:"Canada"},
  {id:"caf", flag:"🇨🇫", name:"Central African Republic"},
  {id:"tcd", flag:"🇹🇩", name:"Chad"},
  {id:"chl", flag:"🇨🇱", name:"Chile"},
  {id:"chn", flag:"🇨🇳", name:"China"},
  {id:"col", flag:"🇨🇴", name:"Colombia"},
  {id:"com", flag:"🇰🇲", name:"Comoros"},
  {id:"cod", flag:"🇨🇩", name:"Congo, Democratic Republic of the"},
  {id:"cog", flag:"🇨🇬", name:"Congo, Republic of the"},
  {id:"cri", flag:"🇨🇷", name:"Costa Rica"},
  {id:"civ", flag:"🇨🇮", name:"Cote d'Ivoire"},
  {id:"hrv", flag:"🇭🇷", name:"Croatia"},
  {id:"cub", flag:"🇨🇺", name:"Cuba"},
  {id:"cyp", flag:"🇨🇾", name:"Cyprus"},
  {id:"cze", flag:"🇨🇿", name:"Czechia"},
  {id:"dnk", flag:"🇩🇰", name:"Denmark"},
  {id:"dji", flag:"🇩🇯", name:"Djibouti"},
  {id:"dma", flag:"🇩🇲", name:"Dominica"},
  {id:"dom", flag:"🇩🇴", name:"Dominican Republic"},
  {id:"ecu", flag:"🇪🇨", name:"Ecuador"},
  {id:"egy", flag:"🇪🇬", name:"Egypt"},
  {id:"slv", flag:"🇸🇻", name:"El Salvador"},
  {id:"gnq", flag:"🇬🇶", name:"Equatorial Guinea"},
  {id:"eri", flag:"🇪🇷", name:"Eritrea"},
  {id:"est", flag:"🇪🇪", name:"Estonia"},
  {id:"swz", flag:"🇸🇿", name:"Eswatini"},
  {id:"eth", flag:"🇪🇹", name:"Ethiopia"},
  {id:"fji", flag:"🇫🇯", name:"Fiji"},
  {id:"fin", flag:"🇫🇮", name:"Finland"},
  {id:"fra", flag:"🇫🇷", name:"France"},
  {id:"gab", flag:"🇬🇦", name:"Gabon"},
  {id:"gmb", flag:"🇬🇲", name:"Gambia"},
  {id:"geo", flag:"🇬🇪", name:"Georgia"},
  {id:"deu", flag:"🇩🇪", name:"Germany"},
  {id:"gha", flag:"🇬🇭", name:"Ghana"},
  {id:"grc", flag:"🇬🇷", name:"Greece"},
  {id:"grd", flag:"🇬🇩", name:"Grenada"},
  {id:"gtm", flag:"🇬🇹", name:"Guatemala"},
  {id:"gin", flag:"🇬🇳", name:"Guinea"},
  {id:"gnb", flag:"🇬🇼", name:"Guinea-Bissau"},
  {id:"guy", flag:"🇬🇾", name:"Guyana"},
  {id:"hti", flag:"🇭🇹", name:"Haiti"},
  {id:"hnd", flag:"🇭🇳", name:"Honduras"},
  {id:"hun", flag:"🇭🇺", name:"Hungary"},
  {id:"isl", flag:"🇮🇸", name:"Iceland"},
  {id:"ind", flag:"🇮🇳", name:"India"},
  {id:"idn", flag:"🇮🇩", name:"Indonesia"},
  {id:"irn", flag:"🇮🇷", name:"Iran"},
  {id:"irq", flag:"🇮🇶", name:"Iraq"},
  {id:"irl", flag:"🇮🇪", name:"Ireland"},
  {id:"isr", flag:"🇮🇱", name:"Israel"},
  {id:"ita", flag:"🇮🇹", name:"Italy"},
  {id:"jam", flag:"🇯🇲", name:"Jamaica"},
  {id:"jpn", flag:"🇯🇵", name:"Japan"},
  {id:"jor", flag:"🇯🇴", name:"Jordan"},
  {id:"kaz", flag:"🇰🇿", name:"Kazakhstan"},
  {id:"ken", flag:"🇰🇪", name:"Kenya"},
  {id:"kir", flag:"🇰🇮", name:"Kiribati"},
  {id:"xkx", flag:"🇽🇰", name:"Kosovo"},
  {id:"kwt", flag:"🇰🇼", name:"Kuwait"},
  {id:"kgz", flag:"🇰🇬", name:"Kyrgyzstan"},
  {id:"lao", flag:"🇱🇦", name:"Laos"},
  {id:"lva", flag:"🇱🇻", name:"Latvia"},
  {id:"lbn", flag:"🇱🇧", name:"Lebanon"},
  {id:"lso", flag:"🇱🇸", name:"Lesotho"},
  {id:"lbr", flag:"🇱🇷", name:"Liberia"},
  {id:"lby", flag:"🇱🇾", name:"Libya"},
  {id:"lie", flag:"🇱🇮", name:"Liechtenstein"},
  {id:"ltu", flag:"🇱🇹", name:"Lithuania"},
  {id:"lux", flag:"🇱🇺", name:"Luxembourg"},
  {id:"mdg", flag:"🇲🇬", name:"Madagascar"},
  {id:"mwi", flag:"🇲🇼", name:"Malawi"},
  {id:"mys", flag:"🇲🇾", name:"Malaysia"},
  {id:"mdv", flag:"🇲🇻", name:"Maldives"},
  {id:"mli", flag:"🇲🇱", name:"Mali"},
  {id:"mlt", flag:"🇲🇹", name:"Malta"},
  {id:"mhl", flag:"🇲🇭", name:"Marshall Islands"},
  {id:"mrt", flag:"🇲🇷", name:"Mauritania"},
  {id:"mus", flag:"🇲🇺", name:"Mauritius"},
  {id:"mex", flag:"🇲🇽", name:"Mexico"},
  {id:"fsm", flag:"🇫🇲", name:"Micronesia"},
  {id:"mda", flag:"🇲🇩", name:"Moldova"},
  {id:"mco", flag:"🇲🇨", name:"Monaco"},
  {id:"mng", flag:"🇲🇳", name:"Mongolia"},
  {id:"mne", flag:"🇲🇪", name:"Montenegro"},
  {id:"mar", flag:"🇲🇦", name:"Morocco"},
  {id:"moz", flag:"🇲🇿", name:"Mozambique"},
  {id:"mmr", flag:"🇲🇲", name:"Myanmar"},
  {id:"nam", flag:"🇳🇦", name:"Namibia"},
  {id:"nru", flag:"🇳🇷", name:"Nauru"},
  {id:"npl", flag:"🇳🇵", name:"Nepal"},
  {id:"nld", flag:"🇳🇱", name:"Netherlands"},
  {id:"nzl", flag:"🇳🇿", name:"New Zealand"},
  {id:"nic", flag:"🇳🇮", name:"Nicaragua"},
  {id:"ner", flag:"🇳🇪", name:"Niger"},
  {id:"nga", flag:"🇳🇬", name:"Nigeria"},
  {id:"prk", flag:"🇰🇵", name:"North Korea"},
  {id:"mkd", flag:"🇲🇰", name:"North Macedonia"},
  {id:"nor", flag:"🇳🇴", name:"Norway"},
  {id:"omn", flag:"🇴🇲", name:"Oman"},
  {id:"pak", flag:"🇵🇰", name:"Pakistan"},
  {id:"plw", flag:"🇵🇼", name:"Palau"},
  {id:"pse", flag:"🇵🇸", name:"Palestine"},
  {id:"pan", flag:"🇵🇦", name:"Panama"},
  {id:"png", flag:"🇵🇬", name:"Papua New Guinea"},
  {id:"pry", flag:"🇵🇾", name:"Paraguay"},
  {id:"per", flag:"🇵🇪", name:"Peru"},
  {id:"phl", flag:"🇵🇭", name:"Philippines"},
  {id:"pol", flag:"🇵🇱", name:"Poland"},
  {id:"prt", flag:"🇵🇹", name:"Portugal"},
  {id:"qat", flag:"🇶🇦", name:"Qatar"},
  {id:"rou", flag:"🇷🇴", name:"Romania"},
  {id:"rus", flag:"🇷🇺", name:"Russia"},
  {id:"rwa", flag:"🇷🇼", name:"Rwanda"},
  {id:"kna", flag:"🇰🇳", name:"Saint Kitts and Nevis"},
  {id:"lca", flag:"🇱🇨", name:"Saint Lucia"},
  {id:"vct", flag:"🇻🇨", name:"Saint Vincent and the Grenadines"},
  {id:"wsm", flag:"🇼🇸", name:"Samoa"},
  {id:"smr", flag:"🇸🇲", name:"San Marino"},
  {id:"stp", flag:"🇸🇹", name:"Sao Tome and Principe"},
  {id:"sau", flag:"🇸🇦", name:"Saudi Arabia"},
  {id:"sen", flag:"🇸🇳", name:"Senegal"},
  {id:"srb", flag:"🇷🇸", name:"Serbia"},
  {id:"syc", flag:"🇸🇨", name:"Seychelles"},
  {id:"sle", flag:"🇸🇱", name:"Sierra Leone"},
  {id:"sgp", flag:"🇸🇬", name:"Singapore"},
  {id:"svk", flag:"🇸🇰", name:"Slovakia"},
  {id:"svn", flag:"🇸🇮", name:"Slovenia"},
  {id:"slb", flag:"🇸🇧", name:"Solomon Islands"},
  {id:"som", flag:"🇸🇴", name:"Somalia"},
  {id:"zaf", flag:"🇿🇦", name:"South Africa"},
  {id:"kor", flag:"🇰🇷", name:"South Korea"},
  {id:"ssd", flag:"🇸🇸", name:"South Sudan"},
  {id:"esp", flag:"🇪🇸", name:"Spain"},
  {id:"lka", flag:"🇱🇰", name:"Sri Lanka"},
  {id:"sdn", flag:"🇸🇩", name:"Sudan"},
  {id:"sur", flag:"🇸🇷", name:"Suriname"},
  {id:"swe", flag:"🇸🇪", name:"Sweden"},
  {id:"che", flag:"🇨🇭", name:"Switzerland"},
  {id:"syr", flag:"🇸🇾", name:"Syria"},
  {id:"twn", flag:"🇹🇼", name:"Taiwan"},
  {id:"tjk", flag:"🇹🇯", name:"Tajikistan"},
  {id:"tza", flag:"🇹🇿", name:"Tanzania"},
  {id:"tha", flag:"🇹🇭", name:"Thailand"},
  {id:"tls", flag:"🇹🇱", name:"Timor-Leste"},
  {id:"tgo", flag:"🇹🇬", name:"Togo"},
  {id:"ton", flag:"🇹🇴", name:"Tonga"},
  {id:"tto", flag:"🇹🇹", name:"Trinidad and Tobago"},
  {id:"tun", flag:"🇹🇳", name:"Tunisia"},
  {id:"tur", flag:"🇹🇷", name:"Turkey"},
  {id:"tkm", flag:"🇹🇲", name:"Turkmenistan"},
  {id:"tuv", flag:"🇹🇻", name:"Tuvalu"},
  {id:"uga", flag:"🇺🇬", name:"Uganda"},
  {id:"ukr", flag:"🇺🇦", name:"Ukraine"},
  {id:"are", flag:"🇦🇪", name:"United Arab Emirates (UAE)"},
  {id:"gbr", flag:"🇬🇧", name:"United Kingdom (UK)"},
  {id:"usa", flag:"🇺🇸", name:"United States of America (USA)"},
  {id:"ury", flag:"🇺🇾", name:"Uruguay"},
  {id:"uzb", flag:"🇺🇿", name:"Uzbekistan"},
  {id:"vut", flag:"🇻🇺", name:"Vanuatu"},
  {id:"vat", flag:"🇻🇦", name:"Vatican City (Holy See)"},
  {id:"ven", flag:"🇻🇪", name:"Venezuela"},
  {id:"vnm", flag:"🇻🇳", name:"Vietnam"},
  {id:"yem", flag:"🇾🇪", name:"Yemen"},
  {id:"zmb", flag:"🇿🇲", name:"Zambia"},
  {id:"zwe", flag:"🇿🇼", name:"Zimbabwe"},
];
