const quotes = [
    ["afg", "The wound is the place where the Light enters you.", "Rumi"],
    ["alb", "The world breaks everyone, and afterward, some are strong at the broken places.", "Ernest Hemingway"],
    ["dza", "In the depth of winter, I finally learned that within me there lay an invincible summer.", "Albert Camus"],
    ["and", "N/A", "N/A"],
    ["ago", "N/A", "N/A"],
    ["atg", "N/A", "N/A"],
    ["arg", "I have always imagined that Paradise will be a kind of library.", "Jorge Luis Borges"],
    ["arm", "N/A", "N/A"],
    ["aus", "There is nothing like looking, if you want to find something.", "J.R.R. Tolkien"],
    ["aut", "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", "Albert Einstein"],
    ["aze", "N/A", "N/A"],
    ["bhs", "N/A", "N/A"],
    ["bhr", "N/A", "N/A"],
    ["bgd", "N/A", "N/A"],
    ["brb", "N/A", "N/A"],
    ["blr", "N/A", "N/A"],
    ["bel", "N/A", "N/A"],
    ["blz", "N/A", "N/A"],
    ["ben", "N/A", "N/A"],
    ["btn", "N/A", "N/A"],
    ["bol", "N/A", "N/A"],
    ["bih", "N/A", "N/A"],
    ["bwa", "N/A", "N/A"],
    ["bra", "The world is round and the place which may seem like the end may also be only the beginning.", "Ivy Baker Priest"],
    ["brn", "N/A", "N/A"],
    ["bgr", "N/A", "N/A"],
    ["bfa", "N/A", "N/A"],
    ["bdi", "N/A", "N/A"],
    ["cpv", "N/A", "N/A"],
    ["khm", "N/A", "N/A"],
    ["cmr", "N/A", "N/A"],
    ["can", "There is a crack in everything. That's how the light gets in.", "Leonard Cohen"],
    ["caf", "N/A", "N/A"],
    ["tcd", "N/A", "N/A"],
    ["chl", "N/A", "N/A"],
    ["chn", "A journey of a thousand miles begins with a single step.", "Laozi"],
    ["col", "N/A", "N/A"],
    ["com", "N/A", "N/A"],
    ["cod", "N/A", "N/A"],
    ["cog", "N/A", "N/A"],
    ["cri", "N/A", "N/A"],
    ["civ", "N/A", "N/A"],
    ["hrv", "N/A", "N/A"],
    ["cub", "N/A", "N/A"],
    ["cyp", "N/A", "N/A"],
    ["cze", "We are all in the gutter, but some of us are looking at the stars.", "Oscar Wilde"],
    ["dnk", "Life itself is the most wonderful fairy tale.", "Hans Christian Andersen"],
    ["dji", "N/A", "N/A"],
    ["dma", "N/A", "N/A"],
    ["dom", "N/A", "N/A"],
    ["ecu", "N/A", "N/A"],
    ["egy", "N/A", "N/A"],
    ["slv", "N/A", "N/A"],
    ["gnq", "N/A", "N/A"],
    ["eri", "N/A", "N/A"],
    ["est", "N/A", "N/A"],
    ["swz", "N/A", "N/A"],
    ["eth", "N/A", "N/A"],
    ["fji", "N/A", "N/A"],
    ["fin", "N/A", "N/A"],
    ["fra", "One must imagine Sisyphus happy.", "Albert Camus"],
    ["gab", "N/A", "N/A"],
    ["gmb", "N/A", "N/A"],
    ["geo", "N/A", "N/A"],
    ["deu", "He who has a why to live can bear almost any how.", "Friedrich Nietzsche"],
    ["gha", "N/A", "N/A"],
    ["grc", "The unexamined life is not worth living.", "Socrates"],
    ["grd", "N/A", "N/A"],
    ["gtm", "N/A", "N/A"],
    ["gin", "N/A", "N/A"],
    ["gnb", "N/A", "N/A"],
    ["guy", "N/A", "N/A"],
    ["hti", "N/A", "N/A"],
    ["hnd", "N/A", "N/A"],
    ["hun", "N/A", "N/A"],
    ["isl", "N/A", "N/A"],
    ["ind", "You must be the change you wish to see in the world.", "Mahatma Gandhi"],
    ["idn", "N/A", "N/A"],
    ["irn", "N/A", "N/A"],
    ["irq", "N/A", "N/A"],
    ["irl", "Being Irish, he had an abiding sense of tragedy, which sustained him through temporary periods of joy.", "W.B. Yeats"],
    ["isr", "N/A", "N/A"],
    ["ita", "The secret of getting ahead is getting started.", "Mark Twain"],
    ["jam", "N/A", "N/A"],
    ["jpn", "Fall seven times, stand up eight.", "Japanese proverb"],
    ["jor", "N/A", "N/A"],
    ["kaz", "N/A", "N/A"],
    ["ken", "N/A", "N/A"],
    ["kir", "N/A", "N/A"],
    ["xkx", "N/A", "N/A"],
    ["kwt", "N/A", "N/A"],
    ["kgz", "N/A", "N/A"],
    ["lao", "N/A", "N/A"],
    ["lva", "N/A", "N/A"],
    ["lbn", "N/A", "N/A"],
    ["lso", "N/A", "N/A"],
    ["lbr", "N/A", "N/A"],
    ["lby", "N/A", "N/A"],
    ["lie", "N/A", "N/A"],
    ["ltu", "N/A", "N/A"],
    ["lux", "N/A", "N/A"],
    ["mdg", "N/A", "N/A"],
    ["mwi", "N/A", "N/A"],
    ["mys", "N/A", "N/A"],
    ["mdv", "N/A", "N/A"],
    ["mli", "N/A", "N/A"],
    ["mlt", "N/A", "N/A"],
    ["mhl", "N/A", "N/A"],
    ["mrt", "N/A", "N/A"],
    ["mus", "N/A", "N/A"],
    ["mex", "N/A", "N/A"],
    ["fsm", "N/A", "N/A"],
    ["mda", "N/A", "N/A"],
    ["mco", "N/A", "N/A"],
    ["mng", "N/A", "N/A"],
    ["mne", "N/A", "N/A"],
    ["mar", "N/A", "N/A"],
    ["moz", "N/A", "N/A"],
    ["mmr", "N/A", "N/A"],
    ["nam", "N/A", "N/A"],
    ["nru", "N/A", "N/A"],
    ["npl", "N/A", "N/A"],
    ["nld", "I know that I am intelligent, because I know that I know nothing.", "Socrates"],
    ["nzl", "N/A", "N/A"],
    ["nic", "N/A", "N/A"],
    ["ner", "N/A", "N/A"],
    ["nga", "The most common way people give up their power is by thinking they don't have any.", "Alice Walker"],
    ["prk", "N/A", "N/A"],
    ["mkd", "N/A", "N/A"],
    ["nor", "I am not afraid of storms, for I am learning how to sail my ship.", "Louisa May Alcott"],
    ["omn", "N/A", "N/A"],
    ["pak", "N/A", "N/A"],
    ["plw", "N/A", "N/A"],
    ["pse", "N/A", "N/A"],
    ["pan", "N/A", "N/A"],
    ["png", "N/A", "N/A"],
    ["pry", "N/A", "N/A"],
    ["per", "N/A", "N/A"],
    ["phl", "N/A", "N/A"],
    ["pol", "Nothing is more powerful than an idea whose time has come.", "Victor Hugo"],
    ["prt", "Everything is worthwhile if the soul is not small.", "Fernando Pessoa"],
    ["qat", "N/A", "N/A"],
    ["rou", "N/A", "N/A"],
    ["rus", "The two most powerful warriors are patience and time.", "Leo Tolstoy"],
    ["rwa", "N/A", "N/A"],
    ["kna", "N/A", "N/A"],
    ["lca", "N/A", "N/A"],
    ["vct", "N/A", "N/A"],
    ["wsm", "N/A", "N/A"],
    ["smr", "N/A", "N/A"],
    ["stp", "N/A", "N/A"],
    ["sau", "N/A", "N/A"],
    ["sen", "N/A", "N/A"],
    ["srb", "N/A", "N/A"],
    ["syc", "N/A", "N/A"],
    ["sle", "N/A", "N/A"],
    ["sgp", "N/A", "N/A"],
    ["svk", "N/A", "N/A"],
    ["svn", "N/A", "N/A"],
    ["slb", "N/A", "N/A"],
    ["som", "N/A", "N/A"],
    ["zaf", "It always seems impossible until it's done.", "Nelson Mandela"],
    ["kor", "N/A", "N/A"],
    ["ssd", "N/A", "N/A"],
    ["esp", "The journey is the reward.", "Steve Jobs"],
    ["lka", "N/A", "N/A"],
    ["sdn", "N/A", "N/A"],
    ["sur", "N/A", "N/A"],
    ["swe", "To be, or not to be, that is the question.", "William Shakespeare"],
    ["che", "N/A", "N/A"],
    ["syr", "N/A", "N/A"],
    ["twn", "N/A", "N/A"],
    ["tjk", "N/A", "N/A"],
    ["tza", "N/A", "N/A"],
    ["tha", "N/A", "N/A"],
    ["tls", "N/A", "N/A"],
    ["tgo", "N/A", "N/A"],
    ["ton", "N/A", "N/A"],
    ["tto", "N/A", "N/A"],
    ["tun", "N/A", "N/A"],
    ["tur", "N/A", "N/A"],
    ["tkm", "N/A", "N/A"],
    ["tuv", "N/A", "N/A"],
    ["uga", "N/A", "N/A"],
    ["ukr", "N/A", "N/A"],
    ["are", "N/A", "N/A"],
    ["gbr", "We are such stuff as dreams are made on.", "William Shakespeare"],
    ["usa", "The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"],
    ["ury", "N/A", "N/A"],
    ["uzb", "N/A", "N/A"],
    ["vut", "N/A", "N/A"],
    ["vat", "N/A", "N/A"],
    ["ven", "N/A", "N/A"],
    ["vnm", "N/A", "N/A"],
    ["yem", "N/A", "N/A"],
    ["zmb", "N/A", "N/A"],
    ["zwe", "N/A", "N/A"]
];
const countryContainer = document.getElementById("countryButtons");

countries.forEach(country => {
    const button = document.createElement("button");

    button.className = "country-button";
    button.textContent = `${country.flag} ${country.name}`;
    button.type = "button";

    button.addEventListener("click", function () {
        const quote = quotes.find(q => q[0] === country.id);

        if (!quote || quote[1] === "N/A") {
            alert("No quote available for this country yet.");
            return;
        }

        document.getElementById("dailyQuote").textContent = quote[1];
        document.getElementById("quoteAuthor").textContent = quote[2];
    });

    countryContainer.appendChild(button);
});
